services:
  tika:
    image: apache/tika:latest
    container_name: opencloud-tika
    networks:
      - opencloud-net
    restart: always

  opencloud:
    image: opencloudeu/opencloud-rolling:latest
    container_name: opencloud
    user: "1000:1000"
    restart: unless-stopped
    environment:
      - OC_URL=https://opencloud.mueller-nas.de
      - OC_INSECURE=true
      - IDM_ADMIN_PASSWORD=admin1234
      - PROXY_TLS=false
      - OC_LOG_LEVEL=info
      - SEARCH_EXTRACTOR_TYPE=tika
      - SEARCH_EXTRACTOR_TIKA_TIKA_URL=http://tika:9998
      - FRONTEND_FULL_TEXT_SEARCH_ENABLED=true
    volumes:
      - /etc/docker/opencloud/config:/etc/opencloud
      - /mnt/opencloud-data:/var/lib/opencloud
    networks:
      - proxy
      - opencloud-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opencloud.entrypoints=https"
      - "traefik.http.routers.opencloud.rule=Host(`opencloud.mueller-nas.de`)"
      - "traefik.http.routers.opencloud.tls.certresolver=cloudflare"
      - "traefik.http.services.opencloud.loadbalancer.server.port=9200"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
  opencloud-net:
    external: true
    name: opencloud_opencloud-net
