services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    user: "1000:1000"
    environment:
      - TZ=Etc/UTC
      - PORT=13378
      - ROUTER_BASE_PATH=/
    volumes:
      - /etc/docker/audiobookshelf:/config
      - /mnt/Mediathek/Hörbücher:/audiobooks
      - /etc/docker/audiobookshelf/metadata:/metadata
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiobookshelf.entrypoints=http"
      - "traefik.http.routers.audiobookshelf.rule=Host(`audiobookshelf.mueller-nas.de`)"
      - "traefik.http.middlewares.audiobookshelf-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.audiobookshelf.middlewares=audiobookshelf-https-redirect"
      - "traefik.http.routers.audiobookshelf-secure.entrypoints=https"
      - "traefik.http.routers.audiobookshelf-secure.rule=Host(`audiobookshelf.mueller-nas.de`)"
      - "traefik.http.routers.audiobookshelf-secure.tls=true"
      - "traefik.http.routers.audiobookshelf-secure.service=audiobookshelf"
      - "traefik.http.services.audiobookshelf.loadbalancer.server.port=13378"
      - "traefik.docker.network=proxy"
    networks:
      proxy:

networks:
  proxy:
    external: true
