services:
  faster-whisper:
    image: lscr.io/linuxserver/faster-whisper:latest
    container_name: faster-whisper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WHISPER_MODEL=medium-int8
      - WHISPER_BEAM=1 #optional
      - WHISPER_LANG=de #optional
    volumes:
      - /mnt/ai/faster-whisper:/config
    # DEBUG: Bei Bedarf mit debug-ports.sh temporär aktivieren
    # ports:
    #   - 10300:10300
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    security_opt:
      - no-new-privileges:true
  
  piper:
    image: lscr.io/linuxserver/piper:latest
    container_name: piper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PIPER_VOICE=de_DE-thorsten-medium
      - PIPER_LENGTH=1.0 #optional
      - PIPER_NOISE=0.667 #optional
      - PIPER_NOISEW=0.333 #optional
      - PIPER_SPEAKER=0 #optional
      - PIPER_PROCS=1 #optional
    volumes:
      - /etc/docker/piper:/config
    # DEBUG: Bei Bedarf mit debug-ports.sh temporär aktivieren
    # ports:
    #   - 10200:10200
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true