networks:
  influxdb:

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    networks:
      - influxdb
    env_file:
      - 'env.influxdb'
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - /var/lib/docker/apps/influxdb:/var/lib/influxdb
      - /var/lib/docker/apps/influxdb2:/var/lib/influxdb2
      - /var/lib/docker/apps/influxdb/etc/influxdb2:/etc/influxdb2
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - influxdb
    env_file:
      - 'env.grafana'
    user: "0"
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - /var/lib/docker/apps/grafana:/var/lib/grafana