services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=${PASSWORD} #optional
      #- HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
      #- SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /etc/docker/vscode:/config
    ports:
      - 8443:8443
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vscodeserver.entrypoints=http"
      - "traefik.http.routers.vscodeserver.rule=Host(`vscodeserver.mueller-nas.de`)"
      - "traefik.http.middlewares.vscodeserver-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.vscodeserver.middlewares=vscodeserver-https-redirect"
      - "traefik.http.routers.vscodeserver-secure.entrypoints=https"
      - "traefik.http.routers.vscodeserver-secure.rule=Host(`vscodeserver.mueller-nas.de`)"
      - "traefik.http.routers.vscodeserver-secure.tls=true"
      - "traefik.http.routers.vscodeserver-secure.service=vscodeserver"
      - "traefik.http.services.vscodeserver.loadbalancer.server.port=8443"
      - "traefik.docker.network=proxy"
    networks:
      proxy:
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true