services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    volumes:
      - /var/lib/docker/apps/homer:/www/assets
    ports:
      - 8181:8080
    environment:
      - INIT_ASSETS=1 # default
    restart: unless-stopped