services:
  faster-whisper:
    image: lscr.io/linuxserver/faster-whisper:latest
    container_name: faster-whisper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WHISPER_MODEL=small-int8
      - WHISPER_BEAM=1 #optional
      - WHISPER_LANG=de #optional
    volumes:
      - /var/lib/docker/apps/faster-whisper:/config
    ports:
      - 10300:10300
    restart: unless-stopped
  
  piper:
    image: lscr.io/linuxserver/piper:latest
    container_name: piper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PIPER_VOICE=de_DE-thorsten-medium
      - PIPER_LENGTH=1.0 #optional
      - PIPER_NOISE=0.667 #optional
      - PIPER_NOISEW=0.333 #optional
      - PIPER_SPEAKER=0 #optional
      - PIPER_PROCS=1 #optional
    volumes:
      - /var/lib/docker/apps/piper:/config
    ports:
      - 10200:10200
    restart: unless-stopped