---
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=PASSWORD
      - CUSTOM_RESULTS=false #optional
      - DB_TYPE=sqlite #optional
      - DB_NAME=DB_NAME #optional
      - DB_HOSTNAME=DB_HOSTNAME #optional
      - DB_USERNAME=DB_USERNAME #optional
      - DB_PASSWORD=DB_PASSWORD #optional
      - DB_PORT=DB_PORT #optional
      - IPINFO_APIKEY=ACCESS_TOKEN #optional
    volumes:
      - /etc/docker/librespeed:/config
    ports:
      - 8383:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librespeed.entrypoints=http"
      - "traefik.http.routers.librespeed.rule=Host(`librespeed.mueller-nas.de`)"
      # - "traefik.http.routers.librespeed.entrypoints=websecure"
      - "traefik.http.middlewares.librespeed-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.librespeed.middlewares=librespeed-https-redirect"
      - "traefik.http.routers.librespeed-secure.entrypoints=https"
      - "traefik.http.routers.librespeed-secure.rule=Host(`librespeed.mueller-nas.de`)"
      - "traefik.http.routers.librespeed-secure.tls=true"
      - "traefik.http.routers.librespeed-secure.service=librespeed"
      - "traefik.http.services.librespeed.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      proxy:
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true