services:
  onedrive:
    container_name: onedrive-sync
    image: driveone/onedrive:edge
    restart: unless-stopped
    #command: --verbose --synchronize --disable-download-validation # old command
    command: --verbose --monitor
    tty: true
    volumes:
      - /OneDrive:/onedrive/data
      - /OneDrive:/home/onedrive/OneDrive
      - /etc/docker/onedrive-sync:/home/onedrive/.config/onedrive
      - /etc/docker/onedrive-sync:/root/.config/onedrive # not sure if this is needed
    environment:
      - PUID=1000
      - PGID=1000
