services:
  onedrive:
    container_name: onedrive-sync
    image: driveone/onedrive:edge
    restart: unless-stopped
    command: --verbose --monitor
    tty: true
    volumes:
      - /mnt/OneDrive:/onedrive/data
      - /mnt/OneDrive:/home/onedrive/OneDrive
      - /etc/docker/onedrive-sync:/home/onedrive/.config/onedrive
      - /etc/docker/onedrive-sync:/root/.config/onedrive # not sure if this is needed
    environment:
      - PUID=1000
      - PGID=1000
    logging: # Docker hat vorher sehr viel geloggt, das war nicht nötig
        driver: none
