version: "3.9"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: Linkwarden-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8889:8888/tcp # HTTP proxy
      - 8389:8388/tcp # Shadowsocks
      - 8389:8388/udp # Shadowsocks
      - 7461:3000
    volumes:
      - /var/lib/docker/apps/gluetun/linkwarden:/gluetun
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkwarden.entrypoints=http"
      - "traefik.http.routers.linkwarden.rule=Host(`linkwarden.mueller-nas.de`)"
      - "traefik.http.middlewares.linkwarden-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.linkwarden.middlewares=linkwarden-https-redirect"
      - "traefik.http.routers.linkwarden-secure.entrypoints=https"
      - "traefik.http.routers.linkwarden-secure.rule=Host(`linkwarden.mueller-nas.de`)"
      - "traefik.http.routers.linkwarden-secure.tls=true"
      - "traefik.http.routers.linkwarden-secure.service=linkwarden"
      - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    security_opt:
      - no-new-privileges:true
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - TZ=Europe/Berlin
    networks:
      - internal
      - proxy
      - external_network
    restart: unless-stopped

  db:
    image: postgres
    container_name: Linkwarden-DB
    hostname: linkwarden-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "linkwarden", "-U", "linkwardenuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /var/lib/docker/apps/postgres/linkwarden:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: linkwarden
      POSTGRES_USER: linkwardenuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure:5
    networks:
      - internal
      - external_network

  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: Linkwarden
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/lib/docker/apps/linkwarden:/data/data
    environment:
      DATABASE_URL: postgres://linkwardenuser:${POSTGRES_PASSWORD}@linkwarden-db:5432/linkwarden
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_DISABLE_REGISTRATION: false # or true
    restart: on-failure:5
    depends_on:
      - gluetun
      - db
    network_mode: service:gluetun

networks:
  proxy:
    external: true
  internal:
    driver: bridge
  external_network:
    external: true
