version: "3.5"
services:
  postgres:
    container_name: linkwardenpostgres
    image: postgres:16-alpine
    restart: always
    volumes:
      - /var/lib/docker/apps/postgres/linkwarden:/var/lib/postgresql/data

  linkwarden:
    container_name: linkwarden
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@linkwardenpostgres:5432/postgres
    restart: always
    # build: . # uncomment this line to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    ports:
      - 3002:3000
    volumes:
      - /var/lib/docker/apps/linkwarden:/data/data
    depends_on:
      - postgres