# Source: https://mariushosting.com/how-to-install-linkwarden-on-your-synology-nas/
version: "3.9"
services:
  db:
    image: postgres
    container_name: Linkwarden-DB
    hostname: linkwarden-db
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "linkwarden", "-U", "linkwardenuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /var/lib/docker/apps/postgres/linkwarden:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: linkwarden
      POSTGRES_USER: linkwardenuser
      POSTGRES_PASSWORD: linkwardenpass
    restart: on-failure:5

  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: Linkwarden
    hostname: linkwarden
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    ports:
      - 7461:3000
    volumes:
      - /var/lib/docker/apps/linkwarden:/data/data
    environment:
      DATABASE_URL: postgres://linkwardenuser:linkwardenpass@linkwarden-db:5432/linkwarden
      NEXTAUTH_SECRET: v6M37byB5LwYHCPZyCJzDGNUSsHY4grj
      NEXTAUTH_URL: http://localhost:3000/api/v1/auth
# Additional Optional Settings
#      PAGINATION_TAKE_COUNT: 
#      STORAGE_FOLDER: 
#      AUTOSCROLL_TIMEOUT: 
      NEXT_PUBLIC_DISABLE_REGISTRATION: false #or true
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy