# Source: https://mariushosting.com/how-to-install-linkwarden-on-your-synology-nas/
version: "3.9"
services:
  db:
    image: postgres
    container_name: Linkwarden-DB
    hostname: linkwarden-db
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "linkwarden", "-U", "linkwardenuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /var/lib/docker/apps/postgres/linkwarden:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: linkwarden
      POSTGRES_USER: linkwardenuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure:5

  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: Linkwarden
    hostname: linkwarden
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    ports:
      - 7461:3000
    volumes:
      - /var/lib/docker/apps/linkwarden:/data/data
    environment:
      DATABASE_URL: postgres://linkwardenuser:${POSTGRES_PASSWORD}@linkwarden-db:5432/linkwarden
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
# Additional Optional Settings
#      PAGINATION_TAKE_COUNT: 
#      STORAGE_FOLDER: 
#      AUTOSCROLL_TIMEOUT: 
      NEXT_PUBLIC_DISABLE_REGISTRATION: false #or true
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkwarden.entrypoints=http"
      - "traefik.http.routers.linkwarden.rule=Host(`linkwarden.mueller-nas.de`)"
      - "traefik.http.middlewares.linkwarden-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.linkwarden.middlewares=linkwarden-https-redirect"
      - "traefik.http.routers.linkwarden-secure.entrypoints=https"
      - "traefik.http.routers.linkwarden-secure.rule=Host(`linkwarden.mueller-nas.de`)"
      - "traefik.http.routers.linkwarden-secure.tls=true"
      - "traefik.http.routers.linkwarden-secure.service=linkwarden"
      - "traefik.http.services.linkwarden.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      proxy:

networks:
  proxy:
    external: true