services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /etc/docker/jellyfin:/config
      - /mnt/transcode/jellyfin:/config/data/transcodes
      - /mnt/Mediathek/Filme:/Filme
      - /mnt/Mediathek/Serien:/Serien
      - /mnt/Mediathek/Anime:/Anime
    extra_hosts:
      - 'host.docker.internal:host-gateway' # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    ports:
      - 8096:8096
      # - 8920:8920 # optional
      - 7359:7359 #/udp #optional
      - 1900:1900 #/udp #optional
    restart: unless-stopped
    #runtime: nvidia
    #deploy:
      #resources:
        #reservations:
          #devices:
            #- driver: nvidia
              #count: 1
              #capabilities: [gpu]
    #devices:
      ##- /dev/nvidia-caps:/dev/nvidia-caps
      #- /dev/nvram:/dev/nvram
      #- /dev/nvidia0:/dev/nvidia0
      #- /dev/nvidiactl:/dev/nvidiactl
      #- /dev/nvidia-modeset:/dev/nvidia-modeset
      #- /dev/nvidia-uvm:/dev/nvidia-uvm
      #- /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=http"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.mueller-nas.de`)"
      - "traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin-https-redirect"
      - "traefik.http.routers.jellyfin-secure.entrypoints=https"
      - "traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.mueller-nas.de`)"
      - "traefik.http.routers.jellyfin-secure.tls=true"
      - "traefik.http.routers.jellyfin-secure.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.docker.network=proxy"
    networks:
      proxy:
    security_opt:
      - no-new-privileges:true

volumes:
  Mediathek_nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.0.10.30,rw,nfsvers=4"   # Ersetze 10.0.10.30 mit der IP deines NFS-Servers sowie ggf. zusätzliche Optionen
      device: ":/mnt/Pool-HDD/Mediathek"  # Ersetze dies mit dem Pfad deines freigegebenen Verzeichnisses vom NFS-Server

networks:
  proxy:
    external: true