version: '3.5'
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    #user: uid:gid
    volumes:
      - /var/lib/docker/apps/jellyfin:/config
      - type: bind
        source: /Mediathek/Filme
        target: /Filme
      - type: bind
        source: /Mediathek/Serien
        target: /Serien
      - type: bind
        source: /Mediathek/Anime
        target: /Anime
    extra_hosts:
      - 'host.docker.internal:host-gateway' # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]