services:
  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - /etc/docker/lazylibrarian:/config
      - /mnt/Mediathek/Buecher:/books
      - /mnt/SABnzbd/downloads/books:/downloads/books
    network_mode: "container:gluetun"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
