services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - /etc/docker/meetube:/downloads
    environment:
      DELETE_FILE_ON_TRASHCAN: true #https://github.com/alexta69/metube/issues/108
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metube.entrypoints=http"
      - "traefik.http.routers.metube.rule=Host(`metube.mueller-nas.de`)"
      - "traefik.http.middlewares.metube-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.metube.middlewares=metube-https-redirect"
      - "traefik.http.routers.metube-secure.entrypoints=https"
      - "traefik.http.routers.metube-secure.rule=Host(`metube.mueller-nas.de`)"
      - "traefik.http.routers.metube-secure.tls=true"
      - "traefik.http.routers.metube-secure.service=metube"
      - "traefik.http.services.metube.loadbalancer.server.port=8081"
      - "traefik.docker.network=proxy"
    networks:
      proxy:
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true