services:
  faster-whisper:
    image: lscr.io/linuxserver/faster-whisper:latest
    container_name: faster-whisper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WHISPER_MODEL=medium
      - WHISPER_BEAM=1 #optional
      - WHISPER_LANG=ger #optional
    volumes:
      - /var/lib/docker/apps/faster-whisper:/config
    ports:
      - 10300:10300
    restart: unless-stopped